### ISSUE TITLE
i cant get it to run

### ISSUE THREAD

**Issue by yousofkakhki** [BoD/bikey#32]
hi ,
tnx for ur effort
in bikey-master\handheld\src\main\java\org\jraf\android\bikey\app\googledrivesync\GoogleDriveSyncActivity.java
there is an import which cannot be resolved
import org.jraf.android.util.app.base.BaseAppCompatActivity;

**Comment by BoD** [comment]
Hi!

I'm sorry you're seeing compilations issues.  I am at work right now so I can't have a look right away, but I will have a look later, tonight.
I sometimes update my JRAF util library, which impacts my apps that depend on it, I know this is bad practice - the proper way to do this is to have releases of the library.

**Comment by yousofkakhki** [comment]
hey  there,
i still cant get it to run  facing the above error
please help
any help would be greatly appreciated

**Comment by BoD** [comment]
Hi!  Sorry for the longer than expected delay.  Everything should compile correctly now.
I'm sorry but I've also changed the names of the keys in build.properties (they have better names now), so you should update them.
